### ISSUE TITLE
[TODO] for beta release  

### ISSUE THREAD

**Issue by Oksydan** [Oksydan/modern-prestashop-starter-theme#7]
## Task list: 

- [x] 1. Setup basic styles for product page.
- [x] 2. Setup basic styles for index page.
- [x] 3. Setup basic styles for listing pages.
- [x] 4. Setup basic styles for supplies/manufacturers page.
- [x] 5. Setup basic styles for checkout page.
- [x] 6. Setup basic styles for cart page.
- [x] 7. Setup basic styles for my account pages.
- [x] 8. Setup basic styles for contact page.
- [x] 10. Add abstract class for importing components dynamically for various scenarios.
- [x] 11. Separate webpack config for develop and production build.
